// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/company-information": {
            "get": {
                "description": "Menggabungkan data website, domain, dan lokasi secara paralel berdasarkan domain perusahaan. Mendukung fallback lokasi jika title website tidak menghasilkan hasil.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Company"
                ],
                "summary": "Get unified company information",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Domain perusahaan (contoh: paper.id)",
                        "name": "domain",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/service.CompanyData"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.APIResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "response.APIResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "error": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "service.CompanyData": {
            "type": "object",
            "properties": {
                "domain": {
                    "$ref": "#/definitions/service.DomainData"
                },
                "location": {
                    "$ref": "#/definitions/service.LocationData"
                },
                "website": {
                    "$ref": "#/definitions/service.WebsiteData"
                }
            }
        },
        "service.DomainData": {
            "type": "object",
            "properties": {
                "domain": {
                    "type": "string"
                },
                "expired_at": {
                    "type": "string"
                },
                "last_updated": {
                    "type": "string"
                },
                "nameservers": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "registered_at": {
                    "type": "string"
                },
                "registrar": {
                    "type": "string"
                },
                "status": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "service.LocationData": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "object",
                    "additionalProperties": true
                },
                "display_name": {
                    "type": "string"
                },
                "importance": {
                    "type": "number"
                },
                "latitude": {
                    "type": "string"
                },
                "longitude": {
                    "type": "string"
                },
                "osm_type": {
                    "type": "string"
                }
            }
        },
        "service.WebsiteData": {
            "type": "object",
            "properties": {
                "canonical": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "emails": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "favicon": {
                    "type": "string"
                },
                "open_graph": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "phones": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "social_media": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "title": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Data Acquisition Engine API",
	Description:      "API untuk ekstraksi metadata website, domain intelligence, dan lokasi geografis.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
